### ISSUE TITLE
19.09.2024 AssertionError: Torch not compiled with CUDA enabled. An attempt to use ZLUDA for Stable Diffusion on windows.

### ISSUE THREAD

**Issue by Harbitos** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#34]
Trying to solve the bug (which is open here - https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/issues/33), I tried to install HIP SDK 5 with RocblasLibs libraries following the instructions from here - https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU I noticed another mistake that I had never seen before. I tried to install it earlier, but there was an error with rocblas, so I used `--directml` and everything worked for me.

All the characteristics and the problem that started it all are described here - https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/issues/33
In that error, `--directml` stopped helping me, I decided to try `--use-zluda`.

**And another question for everyone: has anyone ever run Stable Diffusion Forge with `--use-zluda` on windows?**

```
venv "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 412c2d800dcae4cee8a7466a1e9128cfbbc5bf26
Using ZLUDA in C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\.zluda
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\launch.py", line 58, in <module>
    main()
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\launch.py", line 46, in main
    prepare_environment()
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 608, in prepare_environment
    from modules import devices
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\modules\devices.py", line 3, in <module>
    from backend import memory_management
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\backend\memory_management.py", line 133, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\backend\memory_management.py", line 100, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Press any key to continue . . .
```

**Comment by lshqqytiger** [comment]
You should wipe venv before switching computing backend. Please try again after wiping venv folder.

**Comment by Harbitos** [comment]
> You should wipe venv before switching computing backend. Please try again after wiping venv folder. In addition, why `https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU`? Your card, RX 580, is gfx803, not gfx1103. Maybe [this one](https://github.com/DrENDzZ/ROCmLibs-Fallback) is what you want.

After all this, the SD started, but as in previous problems, it does not generate or write an error after generation.

```
venv "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
ROCm Toolkit 5.7 was found.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 412c2d800dcae4cee8a7466a1e9128cfbbc5bf26
Using ZLUDA in C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\.zluda
Installing requirements
Total VRAM 8192 MB, total RAM 16328 MB
pytorch version: 2.3.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 580 2048SP [ZLUDA] : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
Launching Web UI with arguments: --theme dark --zluda
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ONNX: version=1.19.2 provider=CUDAExecutionProvider, available=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
ZLUDA device failed to pass basic operation test: index=0, device_name=AMD Radeon RX 580 2048SP [ZLUDA]
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

==============================================================================
You are running torch 2.3.0+cu118.
The program is tested to work with torch 2.3.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
ControlNet preprocessor location: C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\models\ControlNetPreprocessor
2024-09-19 18:08:50,714 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'C:\\Users\\user\\Desktop\\Stable Diffusion Forge\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\epicrealism_pureEvolutionV3.safetensors', 'hash': '42c8440c'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 23.1s (prepare environment: 10.1s, import torch: 6.6s, initialize shared: 2.1s, load scripts: 2.4s, create ui: 2.9s, gradio launch: 1.5s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 87.50% GPU memory (7168.00 MB) to load weights, and use 12.50% GPU memory (1024.00 MB) to do matrix computation.
Exception in thread MemMon:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\modules\memmon.py", line 43, in run
    torch.cuda.reset_peak_memory_stats()
  File "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\memory.py", line 309, in reset_peak_memory_stats
    return torch._C._cuda_resetPeakMemoryStats(device)
RuntimeError: invalid argument to reset_peak_memory_stats
Loading Model: {'checkpoint_info': {'filename': 'C:\\Users\\user\\Desktop\\Stable Diffusion Forge\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\epicrealism_pureEvolutionV3.safetensors', 'hash': '42c8440c'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'unet': 686, 'vae': 248, 'text_encoder': 197, 'ignore': 0}
Press any key to continue . . .
```

**Comment by TheFerumn** [comment]
Its 100% something with your PC only since i already tested SD Forge for AMD on 2 different PCs with DirectML and ZLUDA as well. Hard to tell what exactly without errors. Maybe using `--loglevel debug` will show something more ? Its always worth trying.
I don't know which command can actually show you more so just test it yourself.
![Zrzut ekranu 2024-09-19 180033](https://github.com/user-attachments/assets/72c0bcef-0cde-48da-a2f2-167cc0fc43e9)

**Comment by TheFerumn** [comment]
All i can say this error is new to me but i googled a little and it shouldn't be critical. Just wonder why its not showing to me ? Which version of Transformers you have ?

`C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: clean_up_tokenization_spaces was not set. It will be set to True by default. This behavior will be depracted in transformers v4.45, and will be then set to False by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884`

Other than that this might be an issue too but i can't really tell whats the source of it:


```
ZLUDA device failed to pass basic operation test: index=0, device_name=AMD Radeon RX 580 2048SP [ZLUDA]
CUDA error: out of memory
```

**Comment by Harbitos** [comment]
> Все, что я могу сказать, эта ошибка для меня в новинку, но я немного погуглил, и она не должна быть критичной. Просто интересно, почему она мне не отображается? Какая версия Transformers у вас?
> 
> ```
> C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: clean_up_tokenization_spaces was not set. It will be set to True by default. This behavior will be depracted in transformers v4.45, and will be then set to False by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
> ```
> 
> Кроме этого, это тоже может быть проблемой, но я не могу точно сказать, в чем ее источник.:
> 
> ```
> ZLUDA device failed to pass basic operation test: index=0, device_name=AMD Radeon RX 580 2048SP [ZLUDA]
> CUDA error: out of memory
> ```

![Screenshot_3](https://github.com/user-attachments/assets/1bd3e9ca-7845-48da-9adb-b69c37f6ae36)
Maybe it

**Comment by TheFerumn** [comment]
Transformers should be fine. I am afraid i can't help you. Maybe [lshqqytiger](https://github.com/lshqqytiger) knows some methods to find the source of your problem.

My last suggestion is to never use Cyrillic letters or any letters other than english for your folders when using Windows :D
OFC its probably not relevant since it worked for you before. I just had a lot of problems already in the past when using non standard letters in my windows username :D

**Comment by lshqqytiger** [comment]
gfx803 has a bug that the driver occurs out of memory error even if there's enough memory left. This bug is from driver or hip sdk.
You can try upgrading and downgrading graphics driver, but I'm not sure whether it works.

**Comment by lshqqytiger** [comment]
Could you try downgrading torch?
```
.\venv\Scripts\activate
pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118
```
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/issues/479

**Comment by Harbitos** [comment]
> Could you try downgrading torch?
> 
> ```
> .\venv\Scripts\activate
> pip install torch==2.2.1 torchvision==0.17.1 --index-url https://download.pytorch.org/whl/cu118
> ```
> 
> [lshqqytiger/stable-diffusion-webui-amdgpu#479](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/issues/479)

I tried it, all the same. When I first started SD after downgrading the torch version, I got a very long error, and on the second launch everything is as before.

The first launch:

```
venv "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
ROCm Toolkit 5.7 was found.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 412c2d800dcae4cee8a7466a1e9128cfbbc5bf26
Using ZLUDA in C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\.zluda
You are using PyTorch below version 2.3. Some optimizations will be disabled.
Total VRAM 8192 MB, total RAM 16328 MB
pytorch version: 2.2.1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 580 2048SP [ZLUDA] : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
Launching Web UI with arguments: --theme dark --zluda --skip-version-check
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ONNX: version=1.19.2 provider=CUDAExecutionProvider, available=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
ControlNet preprocessor location: C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\models\ControlNetPreprocessor
2024-09-20 11:26:45,767 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'C:\\Users\\user\\Desktop\\Stable Diffusion Forge\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\epicrealism_pureEvolutionV3.safetensors', 'hash': '42c8440c'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 237.9s (prepare environment: 9.3s, import torch: 8.6s, initialize shared: 216.0s, load scripts: 3.1s, create ui: 2.9s, gradio launch: 1.5s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 87.50% GPU memory (7168.00 MB) to load weights, and use 12.50% GPU memory (1024.00 MB) to do matrix computation.
Loading Model: {'checkpoint_info': {'filename': 'C:\\Users\\user\\Desktop\\Stable Diffusion Forge\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\epicrealism_pureEvolutionV3.safetensors', 'hash': '42c8440c'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'unet': 686, 'vae': 248, 'text_encoder': 197, 'ignore': 0}
C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Exception Code: 0xC0000005
0x00007FFEA4572CF4, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x62CF4 byte(s)
0x00007FFEA4571FFC, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x61FFC byte(s)
0x00007FFEA4574497, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x64497 byte(s)
0x00007FFEA457413E, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x6413E byte(s)
0x00007FFEA4573970, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x63970 byte(s)
0x00007FFEA4570E17, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x60E17 byte(s)
0x00007FFEA4570F39, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x60F39 byte(s)
0x00007FFEA4557068, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x47068 byte(s)
0x00007FFEA4518C7C, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x8C7C byte(s)
0x00007FFEA4529183, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\c10.dll(0x00007FFEA4510000) + 0x19183 byte(s)
0x00007FFD0C338B1F, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x6878B1F byte(s)
0x00007FFD0C33ACB6, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x687ACB6 byte(s)
0x00007FFD0C839C8C, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x6D79C8C byte(s)
0x00007FFD0D3272A5, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x78672A5 byte(s)
0x00007FFD0D2E3D1E, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x7823D1E byte(s)
0x00007FFD0CE5642C, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x739642C byte(s)
0x00007FFD0CEB8621, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x73F8621 byte(s)
0x00007FFD0CF862EE, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x74C62EE byte(s)
0x00007FFD0D1E1CC9, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x7721CC9 byte(s)
0x00007FFD0D1DFD5E, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x771FD5E byte(s)
0x00007FFD0CE5642C, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x739642C byte(s)
0x00007FFD0CEF825B, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_cpu.dll(0x00007FFD05AC0000) + 0x743825B byte(s)
0x00007FFE567193AA, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_python.dll(0x00007FFE564B0000) + 0x2693AA byte(s)
0x00007FFE5676A85E, C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\lib\torch_python.dll(0x00007FFE564B0000) + 0x2BA85E byte(s)
0x00007FFEA69149A6, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x649A6 byte(s)
0x00007FFEA68E094E, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x3094E byte(s)
0x00007FFEA68E0A4B, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30A4B byte(s)
0x00007FFEA692D24F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D24F byte(s)
0x00007FFEA6924F15, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x74F15 byte(s)
0x00007FFEA68E0B8C, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30B8C byte(s)
0x00007FFEA68E0A07, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30A07 byte(s)
0x00007FFEA692D24F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D24F byte(s)
0x00007FFEA6924F15, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x74F15 byte(s)
0x00007FFEA68E0B8C, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30B8C byte(s)
0x00007FFEA68E0A07, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30A07 byte(s)
0x00007FFEA692D24F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D24F byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA68E3532, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x33532 byte(s)
0x00007FFEA68E3964, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x33964 byte(s)
0x00007FFEA68E0A83, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30A83 byte(s)
0x00007FFEA692D24F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D24F byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA692D712, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D712 byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA68E3532, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x33532 byte(s)
0x00007FFEA68E3964, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x33964 byte(s)
0x00007FFEA68E6C3F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x36C3F byte(s)
0x00007FFEA692E02B, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7E02B byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA68E0B8C, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30B8C byte(s)
0x00007FFEA68E0A07, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30A07 byte(s)
0x00007FFEA692D24F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D24F byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA68E3532, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x33532 byte(s)
0x00007FFEA68E3964, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x33964 byte(s)
0x00007FFEA68E0A83, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30A83 byte(s)
0x00007FFEA692D24F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D24F byte(s)
0x00007FFEA6924F15, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x74F15 byte(s)
0x00007FFEA6928C0B, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x78C0B byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA69277C4, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x777C4 byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA69277C4, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x777C4 byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA68E0B8C, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30B8C byte(s)
0x00007FFEA68E0A07, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30A07 byte(s)
0x00007FFEA692D24F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D24F byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA692D712, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D712 byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA68E0B30, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30B30 byte(s)
0x00007FFEA68E0A07, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30A07 byte(s)
0x00007FFEA692D24F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D24F byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA69277C4, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x777C4 byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA6928C0B, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x78C0B byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA68E0B30, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30B30 byte(s)
0x00007FFEA68E0A07, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x30A07 byte(s)
0x00007FFEA692D24F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x7D24F byte(s)
0x00007FFEA69280ED, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x780ED byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA6928C0B, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x78C0B byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA69277C4, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x777C4 byte(s)
0x00007FFEA6926267, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x76267 byte(s)
0x00007FFEA69277C4, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x777C4 byte(s)
0x00007FFEA68D9301, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x29301 byte(s)
0x00007FFEA68D7DB2, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x27DB2 byte(s)
0x00007FFEA68D6BFE, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x26BFE byte(s)
0x00007FFEA68D6B7E, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x26B7E byte(s)
0x00007FFEA69C424C, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x11424C byte(s)
0x00007FFEA69C4101, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x114101 byte(s)
0x00007FFEA69C3F04, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x113F04 byte(s)
0x00007FFEA69C3B7F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x113B7F byte(s)
0x00007FFEA69C398F, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x11398F byte(s)
0x00007FFEA69C2F98, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x112F98 byte(s)
0x00007FFEA69C2E29, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x112E29 byte(s)
0x00007FFEA69C27ED, C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll(0x00007FFEA68B0000) + 0x1127ED byte(s)
0x00007FF7EAF61230, C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe(0x00007FF7EAF60000) + 0x1230 byte(s)
0x00007FFECF387344, C:\Windows\System32\KERNEL32.DLL(0x00007FFECF370000) + 0x17344 byte(s)
0x00007FFED04626B1, C:\Windows\SYSTEM32\ntdll.dll(0x00007FFED0410000) + 0x526B1 byte(s)
Press any key to continue . . .
```

The second launch:

```
venv "C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
ROCm Toolkit 5.7 was found.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 412c2d800dcae4cee8a7466a1e9128cfbbc5bf26
Using ZLUDA in C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\.zluda
You are using PyTorch below version 2.3. Some optimizations will be disabled.
Total VRAM 8192 MB, total RAM 16328 MB
pytorch version: 2.2.1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 580 2048SP [ZLUDA] : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
Launching Web UI with arguments: --theme dark --zluda
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ONNX: version=1.19.2 provider=CUDAExecutionProvider, available=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
==============================================================================
You are running torch 2.2.1+cu118.
The program is tested to work with torch 2.3.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
ControlNet preprocessor location: C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\models\ControlNetPreprocessor
2024-09-20 11:29:07,281 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'C:\\Users\\user\\Desktop\\Stable Diffusion Forge\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\epicrealism_pureEvolutionV3.safetensors', 'hash': '42c8440c'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 19.8s (prepare environment: 7.4s, import torch: 6.5s, initialize shared: 1.4s, load scripts: 2.7s, create ui: 3.0s, gradio launch: 1.5s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 87.50% GPU memory (7168.00 MB) to load weights, and use 12.50% GPU memory (1024.00 MB) to do matrix computation.
Loading Model: {'checkpoint_info': {'filename': 'C:\\Users\\user\\Desktop\\Stable Diffusion Forge\\stable-diffusion-webui-amdgpu-forge\\models\\Stable-diffusion\\epicrealism_pureEvolutionV3.safetensors', 'hash': '42c8440c'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'unet': 686, 'vae': 248, 'text_encoder': 197, 'ignore': 0}
C:\Users\user\Desktop\Stable Diffusion Forge\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Press any key to continue . . .
```

**Comment by Harbitos** [comment]
> > AMD driver - 24.3.1 (I kind of installed the latest version and SD used to work for me, but after SD stopped working, installing the latest version or 24.3.1 did not help)
> 
> Have you tried to use AMD Pro Driver ? I feel like it has to be something with your driver since it can't load for you any model no matter which backend you use. The same happens on DirectML and ZLUDA. Torch version doesn't matter as well. It really feels like SD just can't access your memory for some reason. How about adding a lot of swap memory from your SSD drive and launching SD purely on CPU ? Will same thing happen ?

wait, now I message

**Comment by lshqqytiger** [comment]
> Attempt to write pip install torch==2.2.1 torchvision==0.17.1 --index-url https://download.pytorch.org/whl/cu118 led me to the fact that when I generate, it writes endlessly in the console "Compiling in progress, please wait..."
"Compiling in progress, please wait..."
"Compiling in progress, please wait..."
"Compiling in progress, please wait..."
"Compiling in progress, please wait..."

The first launch takes time. (15-20min) Be patient.

**Comment by Harbitos** [comment]
> > Попытка написать pip install torch==2.2.1 torchvision ==0.17.1 --index-url https://download.pytorch.org/whl/cu118 привело меня к тому, что при генерации в консоли бесконечно пишется "Выполняется компиляция, пожалуйста, подождите ..." "Выполняется компиляция, пожалуйста, подождите ..." "Выполняется компиляция, пожалуйста, подождите ..." "Выполняется компиляция, пожалуйста, подождите ..." "Выполняется компиляция, пожалуйста, подождите ...", "Выполняется компиляция, пожалуйста, подождите ...", "Выполняется компиляция, пожалуйста, подождите ...", "Выполняется компиляция, пожалуйста, подождите ...", "Выполняется компиляция, пожалуйста, подождите ...", "Выполняется компиляция, пожалуйста, подождите ...", "Выполняется компиляция, пожалуйста, подождите ...", "Выполняется компиляция, пожалуйста, подождите ...".
> 
> Первый запуск требует времени. (15-20 минут) Наберитесь терпения.

And then it be faster and generate faster?

**Comment by lshqqytiger** [comment]
1. The compilation is one time thing. It does not recompile unless you upgrade/downgrade driver, hip sdk and torch.
2. ZLUDA needs to compile NVIDIA PTX assembly code into the binary (machine language) for AMDGPUs. It will automatically cache compiled binaries.
3. There's no problem.
4. I recommend reinstalling hip sdk if you had overwritten rocmlibs files with wrong files. If the issue persists, check VRAM usage. It could be a kind of out of memory error.

**Comment by Harbitos** [comment]
> 1. The compilation is one time thing. It does not recompile unless you upgrade/downgrade driver, hip sdk and torch.
> 2. ZLUDA needs to compile NVIDIA PTX assembly code into the binary (machine language) for AMDGPUs. It will automatically cache compiled binaries.
> 3. There's no problem.
> 4. I recommend reinstalling hip sdk if you had overwritten rocmlibs files with wrong files. If the issue persists, check VRAM usage. It could be a kind of out of memory error.

It helped! Everything works! I even generated a 1024*1024 image with SDXL model and _Forge Couple_ (Lora didn't have time to try it). But sometimes there were errors, but they disappeared themselves after restarting the SD, 1 time when I generated a 1000*1000 image in inpaint, my monitor went out, the keyboard stopped printing, nothing helped except hard shutdown of the computer. 

Tell me, please, is it normal that this happened to my RX580 graphics card or is something wrong? Or is it accidental and won't happen anymore?

**Comment by TheFerumn** [comment]
It honestly might be just too big resolution for your hardware. I would suggest you to use Hires fix to get higher resolution images.

**Comment by Harbitos** [comment]
> It honestly might be just too big resolution for your hardware. I would suggest you to use Hires fix to get higher resolution images.

And what arguments should I write? Maybe there are certain useful arguments for me or everyone?
`--opt-sub-quad-attention --autolaunch --upcast-sampling `

**Comment by TheFerumn** [comment]
For your GPU i would suggest you to test this commands `--no-half-vae --no-half --upcast-sampling --precision full`
Inpainting probably won't work for you without `--no-half-vae --no-half`
Older GPUs are not optimized to use FP16 (half precision) which uses less VRAM so this commands ensure you use FP32
As far as i know `--opt-sub-quad-attention` doesn't have an effect in Forge but you can force it in settings. I don't quite remember and you probably don't neet it.

**Comment by Harbitos** [comment]
> For your GPU i would suggest you to test this commands `--no-half-vae --no-half --upcast-sampling --precision full` Inpainting probably won't work for you without `--no-half-vae --no-half` Older GPUs are not optimized to use FP16 (half precision) which uses less VRAM so this commands ensure you use FP32 As far as i know `--opt-sub-quad-attention` doesn't have an effect in Forge but you can force it in settings. I don't quite remember and you probably don't need it.

I tried it a couple of times, everything seems to work!
If anything, I was able to generate images in impaint a couple of times before these arguments.

What about questions 2 and 3?

**Comment by TheFerumn** [comment]
> 2. Why doesn't Forge display a preview of the image up to 50%? Is it impossible to open the image during generation as in the original version? Can I fix it?

Go into Settings--User Interface--Live Previews as change what you want
![image](https://github.com/user-attachments/assets/cca371a6-cdf7-4eab-99f3-365d8d73c7fe)

> 3. Why is the Lora preview not displayed on both SD versions? Maybe they are always without previews, but you set the previews yourself?

I think you have to use this extension for it but i am not sure because i never cared about it:
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper

**Comment by Harbitos** [comment]
> > 2. Why doesn't Forge display a preview of the image up to 50%? Is it impossible to open the image during generation as in the original version? Can I fix it?
> 
> Go into Settings--User Interface--Live Previews as change what you want ![image](https://private-user-images.githubusercontent.com/178197881/369707722-cca371a6-cdf7-4eab-99f3-365d8d73c7fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMzEzNzUsIm5iZiI6MTcyNzAzMTA3NSwicGF0aCI6Ii8xNzgxOTc4ODEvMzY5NzA3NzIyLWNjYTM3MWE2LWNkZjctNGVhYi05OWYzLTM2NWQ4ZDczYzdmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxODUxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDZjZGNjMDZlNjA0ZjIyMjI3M2JmN2EyZDM5ZjEwOTQ3MzEwNmY0ZmExMWZhM2IwMTA2OGE5NzJiNjU1NmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GmPVuJEXMRhoOEqxrGjzf1_fDP4xMJeeGIP6t-Qyn2w)
> 
> > 3. Why is the Lora preview not displayed on both SD versions? Maybe they are always without previews, but you set the previews yourself?
> 
> I think you have to use this extension for it but i am not sure because i never cared about it: https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper

Thanks for your answers, thanks **lshqqytiger**! 
I think the issue is closed.
(I will contact you if anything in this chat or create a new issue).

**Comment by Harbitos** [comment]
**Full instructions for how I fixed it:**
Result: I downloaded libraries for RX580 and old graphics cards https://github.com/DrENDzZ/ROCmLibs-Fallback
(HIP SDK 5.7.0 should be installed)
I uploaded the libraries folder from the archive to `C:\Program Files\AMD\ROCm\5.7\bin\rocblas` by renaming the original library to `origibrary`. - All these actions fixed the error `AssertionError: Torch not compiled with CUDA enabled`.

If someone has a situation like mine and does not generate either by writing an error to the console, then I solved it here https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/issues/33

If someone has a `Cuda error: out of memory Compile with 'TORCH_USE_CUDA_DSA' to enable device-side assertions`, then I opened the console in the folder with Stable Diffusion and wrote `pip install torch==2.2.1 torchvision==0.17.1 --index-url https://download.pytorch.org/whl/cu118`. If someone has an error during installation, then try to write as well, but write first `.\venv\Scripts\activate`, and then `pip install torch==2.2.1 torchvision==0.17.1 --index-url https://download.pytorch.org/whl/cu118` . (preferably delete the venv folder before doing so).
