### ISSUE TITLE
broken zluda

### ISSUE THREAD

**Issue by samwys3** [lshqqytiger/stable-diffusion-webui-amdgpu-forge#81]
Hi, I see this commit updated zluda.
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/commit/e0972451b33b589dd95489ab5bb3dfc79cf8e904

My next step would be to attempt a zluda reinstall. I remember my initial install was quite a mission, so don't want to bork it, if that isn't the play...? Any advice would be appreciated, Thank you.

`Already up to date.
venv "N:\StableDiffusion\forge\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: e0972451b33b589dd95489ab5bb3dfc79cf8e904
ROCm: agents=['gfx1032']
ROCm: version=5.7, using agent gfx1032
ZLUDA support: experimental
Failed to load ZLUDA: function 'zluda_get_nightly_flag' not found
Using CPU-only torch
Installing requirements`

the web ui launches but it is not using gpu 

`Launching Web UI with arguments:
Total VRAM 8176 MB, total RAM 16324 MB
pytorch version: 2.3.1+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6600 XT [ZLUDA] : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ONNX: version=1.19.2 provider=CPUExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
ZLUDA device failed to pass basic operation test: index=0, device_name=AMD Radeon RX 6600 XT [ZLUDA]
CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)``

**Comment by samwys3** [comment]
Ok, I replaced the files in the .zluda dir with the latest files from here. https://github.com/lshqqytiger/ZLUDA/releases/  I believe that fixed it...
